language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=development
services:
  - mongodb

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e318bcf9be661aa4311b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


