version: '3'

services:
  app:
    build: ./
    image: odmp
    expose:
      - 80
    environment:
      NODE_ENV: production
      SERVER_PORT: 80
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
